package Bourse;

public enum TypeSecteur {
    TECHNOLOGIE, SANTE, FINANCE, CONSOMMATION_DISCRETIONNAIRE, CONSOMMATION_DE_BASE, ENERGIE, INDUSTRIEL, MATERIAUX, TELECOMMUNICATIONS, UTILITES, IMMOBILIER
}
